### ISSUE TITLE
MVP

### ISSUE THREAD

**Issue by g4s8** [g4s8/wts#1]
Implement MVP:
 - `wts id` - wallet id
 - `wts balance` - wallet balance

**Comment by g4s8** [comment]
@rultor hello

**Comment by g4s8** [comment]
@rultor release, tag=`0.1`

**Comment by g4s8** [comment]
@rultor release, tag=`0.1`

**Comment by g4s8** [comment]
@rultor release, tag=`0.1.1`

**Comment by g4s8** [comment]
@rultor release, tag=`0.1.3`

**Comment by g4s8** [comment]
@rultor release, tag=`0.1.4`

**Comment by 0pdd** [comment]
@g4s8 2 puzzles [#unknown](), [#unknown]() are still not solved.
